#ifndef PATTERN_TRAINER_CONFIG_H
#define PATTERN_TRAINER_CONFIG_H

#define SWEEP_MIN_WAVE 10
#define SWEEP_MAX_WAVE 200

#define GARBAGE_MIN_WAVE 25
#define GARBAGE_MAX_WAVE 100

#define WASH_MIN_WAVE 5
#define WASH_MAX_WAVE 50

enum PATTERN_TYPE{
  P_SWEEP=0x1,
  P_GARBAGE=0x3,
  P_WASH=0x4
};
#endif // PATTERN_TRAINER_CONFIG_H
